### PR TITLE
Update to laravel 7

### PR DESCRIPTION
**Pull request by vv12131415**
Update dependencies to support Laravel 7

### CODE REVIEW

**Comment by vv12131415** [comment]
I would like to get repository rights since I'm the second most active user after you and I always wait for you when new Laravel version comes out.

**Comment by kulbakin** [comment]
@vladyslavstartsev  I sure appreciate your input, there was invite for you pending from quite some time, I guess you've missed it. Issued a new invite for you to become a collaborator.

**Comment by vv12131415** [comment]
@kulbakin sorry for inconvenience, I've missed the invitation. Can you please send one more?

**Comment by kulbakin** [comment]
@vladyslavstartsev sure, sent it again

**Pull request merged**
